In [1]:
import numpy as np

In [2]:
# Numpy -->> Array Manipulaation 

In [3]:
 arr =np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[9, 7, 9, 2],
       [8, 4, 3, 8],
       [3, 5, 9, 2],
       [2, 6, 5, 1]])

In [5]:
arr.reshape(8,2)

array([[9, 7],
       [9, 2],
       [8, 4],
       [3, 8],
       [3, 5],
       [9, 2],
       [2, 6],
       [5, 1]])

In [6]:
arr

array([[9, 7, 9, 2],
       [8, 4, 3, 8],
       [3, 5, 9, 2],
       [2, 6, 5, 1]])

In [7]:
# rotate the entire array row will become column and column will become the row 
arr.T

array([[9, 8, 3, 2],
       [7, 4, 5, 6],
       [9, 3, 9, 5],
       [2, 8, 2, 1]])

In [8]:
arr

array([[9, 7, 9, 2],
       [8, 4, 3, 8],
       [3, 5, 9, 2],
       [2, 6, 5, 1]])

In [9]:
arr.flatten() # create a one dimensional array and put all the data in one dimensional array 

array([9, 7, 9, 2, 8, 4, 3, 8, 3, 5, 9, 2, 2, 6, 5, 1])

In [10]:
np.expand_dims(arr) # missing one argument axis 

TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'

In [11]:
mn = np.expand_dims(arr , axis = 1 ) # so we can see it has converted into the two to three dimension .. here 


In [12]:
mn # so this time it will be converted into the three dimension array 

array([[[9, 7, 9, 2]],

       [[8, 4, 3, 8]],

       [[3, 5, 9, 2]],

       [[2, 6, 5, 1]]])

In [13]:
arr

array([[9, 7, 9, 2],
       [8, 4, 3, 8],
       [3, 5, 9, 2],
       [2, 6, 5, 1]])

In [14]:
np.expand_dims(arr , axis = 0)  # again it will make it a two to  three dimension array but now this time it is row wise 

array([[[9, 7, 9, 2],
        [8, 4, 3, 8],
        [3, 5, 9, 2],
        [2, 6, 5, 1]]])

In [15]:
 data =np.array([[1] , [2] , [3]])

In [16]:
np.squeeze(data) # now it will convert the data into the one dimension array from a two dimension array 

array([1, 2, 3])

In [17]:
np.repeat(data , 2) # it will repeat the data twice 

array([1, 1, 2, 2, 3, 3])

In [18]:
np.repeat(data , 3) # repeat the data thrice 

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
np.repeat(data , 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
np.roll(data ,3) # now it will roll up the entire dataset 

array([[1],
       [2],
       [3]])

In [21]:
np.roll(data , 4)

array([[3],
       [1],
       [2]])

In [24]:
np.roll(data , 2) # one will take two step will roll two time we can say like in the same manner 2 will roll 2 time and 3 will roll 2 time 

array([[2],
       [3],
       [1]])

In [25]:
data

array([[1],
       [2],
       [3]])

In [29]:
np.diag(np.array([1,2,3,4])) # it will make an array with diagonal as [1,2,3,4]

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
# Numpy -- Binary operation 

In [34]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [35]:
arr1

array([[3, 4, 2, 1],
       [4, 9, 3, 2],
       [8, 8, 7, 6]])

In [36]:
arr2

array([[9, 3, 5, 7],
       [2, 7, 1, 9],
       [4, 5, 8, 4]])

In [37]:
# plus minus mul and all sort of operation are known as binary operation ... 

In [38]:
arr1 + arr2 # index wise submission operatrion 

array([[12,  7,  7,  8],
       [ 6, 16,  4, 11],
       [12, 13, 15, 10]])

In [39]:
arr1* arr2

array([[27, 12, 10,  7],
       [ 8, 63,  3, 18],
       [32, 40, 56, 24]])

In [41]:
arr1/arr2 # index wise division operation 

array([[0.33333333, 1.33333333, 0.4       , 0.14285714],
       [2.        , 1.28571429, 3.        , 0.22222222],
       [2.        , 1.6       , 0.875     , 1.5       ]])

In [43]:
arr1-arr2 # index wise subraction 

array([[-6,  1, -3, -6],
       [ 2,  2,  2, -7],
       [ 4,  3, -1,  2]])

In [44]:
arr1 ** arr2 # index wise power operation it is doing 

array([[  19683,      64,      32,       1],
       [     16, 4782969,       3,     512],
       [   4096,   32768, 5764801,    1296]], dtype=int32)

In [45]:
~arr1 # index wise binary negation operation 

array([[ -4,  -5,  -3,  -2],
       [ -5, -10,  -4,  -3],
       [ -9,  -9,  -8,  -7]], dtype=int32)

In [46]:
arr1

array([[3, 4, 2, 1],
       [4, 9, 3, 2],
       [8, 8, 7, 6]])

In [48]:
arr1 > arr2 # index wise comparison 

array([[False,  True, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [49]:
# Numpy - sting operation 

In [50]:
arr = np.asarray(['shudh' , 'kumar'])

In [52]:
arr # data type u5 means string type of the dataset .. 

array(['shudh', 'kumar'], dtype='<U5')

In [53]:
# if we want to change the string data into the uppercase()

In [55]:
np.char.upper(arr) # char stands for character and in the car operation there are all the operation related to string 

array(['SHUDH', 'KUMAR'], dtype='<U5')

In [58]:
np.char.capitalize(arr) # first letter it will keep in upper case and other it will take in lower case 

array(['Shudh', 'Kumar'], dtype='<U5')

In [59]:
np.char.title(arr)

array(['Shudh', 'Kumar'], dtype='<U5')

In [60]:
# numpy - mathematical operation 

In [61]:
arr1

array([[3, 4, 2, 1],
       [4, 9, 3, 2],
       [8, 8, 7, 6]])

In [62]:
np.sin(arr1) # give the sin value of all this data 

array([[ 0.14112001, -0.7568025 ,  0.90929743,  0.84147098],
       [-0.7568025 ,  0.41211849,  0.14112001,  0.90929743],
       [ 0.98935825,  0.98935825,  0.6569866 , -0.2794155 ]])

In [63]:
np.cos(arr1) # give all the cos values 

array([[-0.9899925 , -0.65364362, -0.41614684,  0.54030231],
       [-0.65364362, -0.91113026, -0.9899925 , -0.41614684],
       [-0.14550003, -0.14550003,  0.75390225,  0.96017029]])

In [65]:
np.tan(arr1) # give us the tan value 

array([[-0.14254654,  1.15782128, -2.18503986,  1.55740772],
       [ 1.15782128, -0.45231566, -0.14254654, -2.18503986],
       [-6.79971146, -6.79971146,  0.87144798, -0.29100619]])

In [66]:
np.log10(arr1) # give us the log value 

array([[0.47712125, 0.60205999, 0.30103   , 0.        ],
       [0.60205999, 0.95424251, 0.47712125, 0.30103   ],
       [0.90308999, 0.90308999, 0.84509804, 0.77815125]])

In [67]:
np.exp(arr1) # give us the exponent of the data 

array([[2.00855369e+01, 5.45981500e+01, 7.38905610e+00, 2.71828183e+00],
       [5.45981500e+01, 8.10308393e+03, 2.00855369e+01, 7.38905610e+00],
       [2.98095799e+03, 2.98095799e+03, 1.09663316e+03, 4.03428793e+02]])

In [69]:
np.power(arr1 , 2) # find the sq of every element and return thee values 

array([[ 9, 16,  4,  1],
       [16, 81,  9,  4],
       [64, 64, 49, 36]], dtype=int32)

In [70]:
np.power(arr1 , 4)

array([[  81,  256,   16,    1],
       [ 256, 6561,   81,   16],
       [4096, 4096, 2401, 1296]], dtype=int32)

In [71]:
np.mean(arr1) # give the mean value of the entire array 

4.75

In [72]:
np.median(arr1) # give the median value of the entire array 

4.0

In [73]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [74]:
np.std(arr1) # give us the standard deveation of whole array 

2.6180463454008347

In [75]:
np.var(arr1) # give us the variance of whole array 

6.854166666666667

In [76]:
np.min(arr1) # give the minimum value 

1

In [77]:
np.max(arr1) # give us the maximum value 

9

In [78]:
# Numpy - airhtmetic operation 

In [79]:
arr1

array([[3, 4, 2, 1],
       [4, 9, 3, 2],
       [8, 8, 7, 6]])

In [80]:
arr2

array([[9, 3, 5, 7],
       [2, 7, 1, 9],
       [4, 5, 8, 4]])

In [81]:
arr1 - arr2

array([[-6,  1, -3, -6],
       [ 2,  2,  2, -7],
       [ 4,  3, -1,  2]])

In [83]:
np.subtract(arr1 , arr2) # in the same way numoy also have a same function for subtraction 

array([[-6,  1, -3, -6],
       [ 2,  2,  2, -7],
       [ 4,  3, -1,  2]])

In [84]:
np.multiply(arr1 , arr2)

array([[27, 12, 10,  7],
       [ 8, 63,  3, 18],
       [32, 40, 56, 24]])

In [86]:
np.mod(arr1 , arr2) # mod is nothing just give us the remainder 

array([[3, 1, 2, 1],
       [0, 2, 0, 2],
       [0, 3, 7, 2]], dtype=int32)

In [87]:
np.power(arr1 , arr2)

array([[  19683,      64,      32,       1],
       [     16, 4782969,       3,     512],
       [   4096,   32768, 5764801,    1296]], dtype=int32)

In [88]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 1.41421356, 1.        ],
       [2.        , 3.        , 1.73205081, 1.41421356],
       [2.82842712, 2.82842712, 2.64575131, 2.44948974]])

In [89]:
# numpy - statistical operation 

In [90]:
arr1

array([[3, 4, 2, 1],
       [4, 9, 3, 2],
       [8, 8, 7, 6]])

In [91]:
np.mean(arr1)

4.75

In [92]:
np.std(arr1)

2.6180463454008347

In [93]:
np.median(arr1)

4.0

In [94]:
import numpy as np 

In [95]:
# sort  , search and counting function 

In [115]:
arr = np.array([72,33,44,5,61,71])

In [103]:
np.sort(arr) # ascending order 

array([ 5, 33, 44, 61, 71, 72])

In [110]:
np.searchsorted(arr, 6) # it will give us the index to store the 6 in a sorted manner to existing array  

1

In [111]:
np.searchsorted(arr , 77)

6

In [112]:
np.searchsorted(arr , 4)

0

In [114]:
arr1 = np.array([0,324,645,66,0,0,0,234])

In [116]:
#counting function 
np.count_nonzero(arr1) # return the name of non zero element 

4

In [118]:
np.where(arr1 >0)# at what indexed we have data greater than 0 

(array([1, 2, 3, 7], dtype=int64),)

In [122]:
np.extract(arr1> 2 , arr1) # it is trying to ectract all the data greater than 2 

array([324, 645,  66, 234])

In [123]:
# numpy - Byte swapping
arr1 

array([  0, 324, 645,  66,   0,   0,   0, 234])

In [125]:
# we don't used it generally 
arr1.byteswap() # swpa the original data with the byte one 

array([          0,  1140916224, -2063466496,  1107296256,           0,
                 0,           0,  -369098752])

In [126]:
# if we want to keep the byte data permanent then-->>
arr1.byteswap(True) # it will make inplace = True

array([          0,  1140916224, -2063466496,  1107296256,           0,
                 0,           0,  -369098752])

In [127]:
arr1

array([          0,  1140916224, -2063466496,  1107296256,           0,
                 0,           0,  -369098752])

In [128]:
# numpy - copy and view

In [129]:
arr2 = np.array([1,34,55,4,34,23,12,27,76])

In [130]:
a = np.copy(arr2)# this will make the deep copy 

In [131]:
a # if we do any changes in arr2 then it will not affect the a 

array([ 1, 34, 55,  4, 34, 23, 12, 27, 76])

In [135]:
# view
b = arr2.view()

In [137]:
b # the changes we do in b and arr2 will effect each other now 

array([ 1, 34, 55,  4, 34, 23, 12, 27, 76])

In [138]:
b[0] = 2

In [139]:
b

array([ 2, 34, 55,  4, 34, 23, 12, 27, 76])

In [140]:
arr2

array([ 2, 34, 55,  4, 34, 23, 12, 27, 76])

In [141]:
arr2[0] = 1

In [142]:
arr2

array([ 1, 34, 55,  4, 34, 23, 12, 27, 76])

In [143]:
b

array([ 1, 34, 55,  4, 34, 23, 12, 27, 76])

In [144]:
# view operation is just like b = arr2 # ditto same 

In [145]:
# Numpy - matrix library 

In [147]:
import numpy.matlib as nm # matlib stands for matrix library 

In [149]:
nm.zeros(5) # it will create a two dimensional matrix 

matrix([[0., 0., 0., 0., 0.]])

In [151]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [152]:
# matrix is a subset of an array inside numpy 

In [154]:
nm.eye(4) # matrix with all diagonal as 1 

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [155]:
# whatever we can achieve in the matrix library we can achieve in the numpy library 

In [156]:
# Numpy -- Linear algebra

In [157]:
arr1

array([          0,  1140916224, -2063466496,  1107296256,           0,
                 0,           0,  -369098752])

In [158]:
arr1=np.random.randint([[2,3] , [4,5]])
arr2=np.random.randint([[5,3] , [2,5]])

In [159]:
arr1

array([[1, 0],
       [0, 3]])

In [160]:
arr2

array([[3, 1],
       [1, 4]])

In [161]:
np.dot(arr1, arr2)

array([[ 3,  1],
       [ 3, 12]])

In [162]:
arr1@arr2 # dot product is nothing but just a matrix multiplication 

array([[ 3,  1],
       [ 3, 12]])